name: PR Test

on:
  pull_request:
    branches:
      - main

jobs:
  build:
    name: Lint & Build
    runs-on: ubuntu-latest
    steps:
      - name: Git Checkout
        uses: actions/checkout@v2
      - name: Install deps
        run: yarn --frozen-lockfile
      - name: Run lint
        run: yarn lint
      - name: Run production build
        run: yarn build
      - name: Run e2e tests
        run: yarn e2e:run
